### ISSUE TITLE
Should refresh list of modified files when switching branches

### ISSUE THREAD

**Issue by tkiethanom** [letmaik/vscode-git-tree-compare#32] opened 2018-01-12 22:53 UTC
List of modified files is not refreshed when checking out another branch in the main code explorer. Clicking `Refresh` doesn't do anything either. 

Temporary solution, `Change Base...` to any another branch and then change it back to the branch you want to compare against.

**Comment by letmaik** [comment] 2018-01-14 10:13
That should work, so it's definitely a bug. Which VS Code version are you on? Also, which OS and which git version? Are you using git worktree by any chance?

**Comment by tkiethanom** [comment] 2018-01-16 23:19
VS Code: 1.19.2
OS: Mac OS Sierra 10.12.4
Git Tree Compare: 1.1.4

**Comment by letmaik** [comment] 2018-01-31 17:50
I couldn't reproduce this. Can you let me know if there is any relevant output in the "Git Tree Compare" section of the Output tab (View -> Output)? Similarly, do you see any errors in Help -> Toggle Developer Tools -> Console?

**Comment by tkiethanom** [comment] 2018-01-31 21:36
I'm using VS Code 1.19.3 now and it's still happening. Nothing in the Output or Developer Tools Console either. I guess I'll just assume it's just my problem until someone has a similar issue.

**Comment by letmaik** [comment] 2018-01-31 22:45
Strange! If you're up for it we could do some Skype (or whatever) remote desktop debugging. I would be interested in getting to the bottom of this. Just send me an email (see profile) if you like.

**Comment by tkiethanom** [comment] 2018-01-31 23:51
Maybe I can send you a video later

**Comment by karlsson-github** [comment] 2018-02-09 15:01
I had the same problem. Then I updated to VS Code 1.20.0 and now it works:

VS Code: 1.20.0
OS: Mac OS Sierra 10.12.6
Git: 2.13.5 (Apple Git-94)
Git Tree Compare: 1.1.4

**Comment by tkiethanom** [comment] 2018-02-09 22:00
@karlsson-github do you have any issues where the file tree is not expanded? So you have to expand each one manually?

**Comment by karlsson-github** [comment] 2018-02-10 04:11
@tkiethanom, nope. Expansion works fine for me.

**Comment by letmaik** [comment] 2018-02-10 10:07
@tkiethanom Is that the case when you have a `/` node?

**Comment by tkiethanom** [comment] 2018-02-12 20:35
@letmaik can you explain what you mean by `/` node?

**Comment by letmaik** [comment] 2018-02-13 07:49
@tkiethanom A `/` node is used when you open a subfolder of your repository as workspace folder and you have changes outside of that subfolder. Ignore that if it doesn't apply to you. Do the issues (expansion, and not refreshing) still exist for you with VS Code 1.20?

**Comment by tkiethanom** [comment] 2018-02-13 17:58
@letmaik No I'm not doing anything with subfolders. My .git directory is in the root of my VScode project. I think 1.20 has fixed my issues.

**Comment by letmaik** [comment] 2018-02-13 18:26
OK let's close this for now. If it happens again, just comment here and I'll reopen the issue.

**Closed by letmaik** 2018-02-13 18:26 UTC
Labels: bug

**Comment by msorens** [comment] 2018-12-12 15:51
This same thing happens for me quite frequently--but not all the time, which of course makes it challenging to track down. I have seen this for months, ever since I installed the plugin, across multiple versions of VSCode as new updates have come out. Very roughly it happens half the time. Unfortunately, I have not been able to narrow down the circumstances of when it occurs.

The workaround mentioned above (`Change base` elsewhere, then back again) allows a proper refresh.

VS Code: 1.29.1
OS: Mac OS High Sierra 10.13.6
Git: 2.15.1
Git Tree Compare: 1.4.0

**Comment by letmaik** [comment] 2018-12-12 22:20
Please in those cases observe the View -> Output tab for this extension. When you switch branches then there should be some output, and it lists the git commands it executes and whether those resulted in changes to the diff tree. Maybe that helps in diagnosing this.

**Comment by msorens** [comment] 2019-08-05 16:34
Sorry, had forgotten I commented here. This issue is still happening for me, and it happens most of the time. (Now using VSCode 1.36.1)

One common characteristic I have identified: the failure to refresh occurs when switching from one _non_-master branch to another _non_-master branch (though not every time!)

Here's a transcript of the extension output showing three branch switches:
first from `sr/issue-1129` to `ms/update-rules-check-perm` where Git Tree Compare did _not_ update:
```
Updating refs
> git symbolic-ref --short HEAD
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git merge-base master ms/update-rules-check-perm
HEAD ref updated: sr/issue-1129 -> ms/update-rules-check-perm
HEAD ref commit updated: 5512d2ae4f76f832fb3332f2a6beafdb1f4a2247 -> dffd2094e4bcb2523714fad3a133eee53a93924d
Merge base updated: c5b685c65cbb5b8f72e301ebea6a289699c8b272 -> 836df207d822b3c4f88b32b68efa986fd52962db
> git update-index --refresh -q
> git diff-index --no-renames 836df207d822b3c4f88b32b68efa986fd52962db --
> git ls-files --others --exclude-standard
1 diff entries
No tree changes
```
Then from there to `master`, where Git Tree Compare refreshed correctly:
```
Updating refs
> git symbolic-ref --short HEAD
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
HEAD ref updated: ms/update-rules-check-perm -> master
HEAD ref commit updated: dffd2094e4bcb2523714fad3a133eee53a93924d -> 8a40747d7955b7ac43fd547ae35bdb2fd274e3c6
Merge base updated: 836df207d822b3c4f88b32b68efa986fd52962db -> master
> git update-index --refresh -q
> git diff-index --no-renames master --
> git ls-files --others --exclude-standard
0 diff entries
No tree changes
```
And finally back to the previous branch, where Git Tree Compare refreshed correctly:
```
Updating refs
> git symbolic-ref --short HEAD
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git merge-base master ms/update-rules-check-perm
HEAD ref updated: master -> ms/update-rules-check-perm
HEAD ref commit updated: 8a40747d7955b7ac43fd547ae35bdb2fd274e3c6 -> dffd2094e4bcb2523714fad3a133eee53a93924d
Merge base updated: master -> 836df207d822b3c4f88b32b68efa986fd52962db
> git update-index --refresh -q
> git diff-index --no-renames 836df207d822b3c4f88b32b68efa986fd52962db --
> git ls-files --others --exclude-standard
1 diff entries
No tree changes
```
With several more trials, I note that if `master` is involved in the branch change, it always refreshes correctly. If `master` is not involved it usually--but not always--fails to refresh.

**Comment by letmaik** [comment] 2019-08-05 19:08
OK that's great. Please try to keep these branches so that we have something reproducible (maybe make a copy of the repo). I still don't know where the issue is but what I would suggest is that you manually run the `git diff-index` command from the log for the case where the refresh didn't work. If the output of that really doesn't match the tree then we have a bug. If it does match, then it may be something related to how we use git (merge bases etc.).

**Comment by msorens** [comment] 2019-08-05 21:48
Might be getting somewhere. I created and switched to a new branch, then committed two files. Going back and forth to master, the tree was updating correctly. I believe it is because the branch is rooted in the most current commit on master! From that new branch (showing just 2 files changed in the tree), I then went to the earlier branch I mentioned above--sr/issue-1129. No tree refresh. Copying the `git diff-index` from the output window I got a list of more than 50 files (when it should be 6 files).

**Comment by letmaik** [comment] 2019-08-06 04:02
Would it be possible to recreate this scenario in a fresh repo and push that to github?

**Comment by msorens** [comment] 2019-08-06 16:07
Per your suggestion, I tried a fresh repo but, alas, I am not able to reproduce the issue there yet. So let me offer you a suggestion: you can pull down my real repo (https://github.com/chef/automate -- it's open source) and just try switching amongst any of the myriad branches. (Note  that branches are automatically deleted upon merge so they come and go.)

**Comment by letmaik** [comment] 2019-08-06 18:52
For chef/automate, can you give me a concrete example I can try? The branches you mentioned earlier are gone already. I tried switching around a bit but couldn't notice anything unusual yet.

**Comment by msorens** [comment] 2019-08-06 21:12
Try this:
```
$ git ck ms/form-field-watcher
<A> <-- switch window to VSCode: tree correctly refreshes
$ git ck master
<B> <-- DO NOT switch window to VSCode
$ git ck dan/plain-nats-hab-hc
<C> <-- switch window to VSCode: tree does NOT refresh
```
Note that if you look at VSCode at <B> then it will correctly refresh both at <B> and at <C>.

**Comment by letmaik** [comment] 2019-08-07 21:14
I just tried this and as expected at `<B>` the tree doesn't refresh as the window is out of scope (this is intended). However, I also get the correct behaviour at `<C>`.
If you're up for it we could have a quick skype session tomorrow afternoon (morning for you I guess). Send me an email if interested.
