### ISSUE TITLE
"Open All Changes" does not open added files, only modified files

### ISSUE THREAD

**Issue by amituuush** [letmaik/vscode-git-tree-compare#47] opened 2019-03-18 23:37 UTC
Not sure if this is intended functionality, but it would save time if there was a way to open **all** files whether added or modified.

"Open Changed Files" does open added files; however, it does not open modified files with color coded diff, which is what I use to see what's changed in a file.

**Comment by letmaik** [comment] 2019-03-19 00:51
Can't reproduce, for me "Open All Changes" also opens added files, which is the intended behaviour. Can you check again?

**Comment by amituuush** [comment] 2019-03-19 20:12
@letmaik yeah no luck :/ same result

**Comment by letmaik** [comment] 2019-03-19 23:08
I'm not sure what it could be. Would it possible for you to create a (minimal) repository folder that demonstrates this behaviour and upload it here as zip?

**Comment by amituuush** [comment] 2019-04-03 18:15
@letmaik apologies for the late reply -- I created a test repo and all files opened (including added files). However, added files don't open in my company's repository. Unfortunately, I can't upload that here (for obvious reasons). Not a huge deal, I can simply click the added files and they open but thought it was worth mentioning here.

**Comment by letmaik** [comment] 2019-04-03 18:34
OK thanks for reporting. Without something to reproduce this will be hard. I'm going to close this for now until someone else reports the same.

**Closed by letmaik** 2019-04-03 18:34 UTC
